client:
  plotting:
    urls:
      NPclassifier: 'https://npclassifier.ucsd.edu/classify?smiles='
      classyfire: 'https://gnps-structure.ucsd.edu/classyfire?smiles='

  host:
    prod: "https://app.omigami.com/"